name: Build and Upload Artifacts

on:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - goos: windows
            goarch: amd64
            ext: .exe
          - goos: linux
            goarch: amd64
            ext: ""
          - goos: darwin
            goarch: arm64
            ext: ""

    outputs:
      tag: ${{ steps.extract_tag.outputs.tag }}

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'

      - name: Build for ${{ matrix.goos }}/${{ matrix.goarch }}
        env:
          GOOS: ${{ matrix.goos }}
          GOARCH: ${{ matrix.goarch }}
        run: |
          mkdir -p build/${{ matrix.goos }}_${{ matrix.goarch }}
          go build -o build/${{ matrix.goos }}_${{ matrix.goarch }}/tree-size${{ matrix.ext }} .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        if: github.ref == 'refs/heads/main'
        with:
          name: tree-size-${{ matrix.goos }}-${{ matrix.goarch }}
          path: build/${{ matrix.goos }}_${{ matrix.goarch }}

      - name: Save build output for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          mkdir -p release
          cp build/${{ matrix.goos }}_${{ matrix.goarch }}/tree-size${{ matrix.ext }} release/tree-size-${{ matrix.goos }}-${{ matrix.goarch }}${{ matrix.ext }}

  release:
    if: startsWith(github.ref, 'refs/tags/')
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            artifacts/tree-size-windows-amd64/tree-size.exe
            artifacts/tree-size-linux-amd64/tree-size
            artifacts/tree-size-darwin-arm64/tree-size
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
